catamiPortal/urls.py
"""@brief Django URLs for main Catami views.

Created Mark Gray 10/09/2012
markg@ivec.org

Edits :: Name : Date : description

"""
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'catamiPortal.views.home', name='home'),
                       # url(r'^catamiPortal/', include('catamiPortal.foo.urls')),

                       url(r'^$', 'catamiPortal.views.index'),
                       url(r'^api/', include('jsonapi.urls')),
                       url(r'^faq', 'catamiPortal.views.faq'),
                       url(r'^contact', 'catamiPortal.views.contact'),
                       url(r'^attribution', 'catamiPortal.views.attribution'),
                       url(r'^proxy/(?P<url>.*)$', 'catamiPortal.views.proxy'),


                       url(r'^staging/', include('staging.urls')),

                       url(r'images/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.IMAGES_ROOT, 'show_indexes': True}),

                       url(r'^webinterface/', include('webinterface.urls')),

                       #to hide the database name
                       url(r'^data/', include('Force.urls')),

                       #haystack
                       #url(r'^search/', include('haystack.urls')),

                       # plots
                       url(r'^report/', include('dbadmintool.urls')),

                       # userena
                       (r'^accounts/', include('accounts.urls')),

                       #dbadmin tool

                       # Uncomment the admin/doc line below to enable admin documentation:
                       # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^accounts/login/$', 'django.contrib.auth.views.login',
                           {'template_name': 'registration/login.html'}),
                       url(r'^logout/$', 'catamiPortal.views.logout_view'),
)

feedback/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import ListView, DetailView

urlpatterns = patterns('feedback.views',
    url(r'^add$', 'add'),
    url(r'^list$', 'request_list'),
    url(r'^view/(?P<pk>\d+)$', 'view'),
    url(r'^edit/(?P<pk>\d+)$', 'edit'),
    url(r'^delete/(?P<pk>\d+)$', 'delete'),
)

jsonapi/urls.py
from copy import copy
from django.conf.urls import patterns, include, url
from tastypie.api import Api
from tastypie.resources import Resource
import collection.api
import catamidb.api
import jsonapi.api
import staging.api
import annotations.api

# monkey patch the Resource init method to remove a particularly cpu hungry deepcopy
def patched_resource__init__(self, api_name=None):
    #self.fields = deepcopy(self.base_fields)
    self.fields = {k: copy(v) for k, v in self.base_fields.iteritems()}

    if not api_name is None:
        self._meta.api_name = api_name

Resource.__init__ = patched_resource__init__

dev_api = Api(api_name='dev')
v1_api = Api(api_name='v1')

dev_api.register(collection.api.CollectionResource())
dev_api.register(catamidb.api.CampaignResource())
dev_api.register(catamidb.api.DeploymentResource())
dev_api.register(catamidb.api.PoseResource())
dev_api.register(catamidb.api.SimplePoseResource())
dev_api.register(catamidb.api.ImageResource())
dev_api.register(catamidb.api.ScientificImageMeasurementResource())
dev_api.register(catamidb.api.ScientificPoseMeasurementResource())
dev_api.register(catamidb.api.ScientificMeasurementTypeResource())

dev_api.register(jsonapi.api.UserResource())

dev_api.register(staging.api.StagingFilesResource())

dev_api.register(annotations.api.AnnotationCodeResource())
dev_api.register(annotations.api.QualifierCodeResource())
dev_api.register(annotations.api.PointAnnotationSetResource())
dev_api.register(annotations.api.PointAnnotationResource())

urlpatterns = patterns('',
                       (r'^$', 'jsonapi.views.help'),
                       (r'', include(dev_api.urls)),
                       (r'', include(v1_api.urls)),
)

staging/urls.py
"""URL Mappings for the staging application.
"""
__author__ = 'Lachlan Toohey'

from django.conf.urls import patterns, url
#from django.contrib.auth.models import User

urlpatterns = patterns('staging.views',
                       url(r'^$', 'index', name='staging_index'),

                       # campaign creating
                       url(r'^campaign/create$', 'campaigncreate',
                           name='staging_campaign_create'),
                       url(r'^campaign/created$', 'campaigncreated',
                           name='staging_campaign_created'),

                       url(r'^browse$', 'newbrowse'),
                       url(r'^create/auv/(?P<pk>\w[\w-]*)$', 'api_auv_form',
                           name='api_auv_form')
)

annotations/models.py
"""Data models for the annotation component.
"""
from django.db import models
from django.contrib.auth.models import User
from collection.models import Collection
from authorization import apply_pointannotationset_permissions



class AnnotationCode(models.Model):
    """The base annotation (CAAB) structure.
    
    This stores all the levels of the classifaction tree
    with parent filled in as appropriate.
    """
    caab_code = models.CharField(max_length=8, blank=True, null=True, unique=True) # 8 numbers
    cpc_code = models.CharField(max_length=6, unique=True) # CPC Code file code
    point_colour = models.CharField(max_length=6) # hex RGB colour
    code_name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    parent = models.ForeignKey(
            'annotations.AnnotationCode',
            blank=True,
            null=True
        )

    def __unicode__(self):
        return "{0} - ({1})".format(self.code_name, self.caab_code)


class QualifierCode(models.Model):
    """Qualifiers to annotations.

    Examples include anthropogenic labels, or natural labels
    that include bleaching, dead etc.
    """
    modifier_name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)

    def __unicode__(self):
        return self.modifier_name

class AnnotationSet(models.Model):
    """The common base for Point and Whole image annotation sets.
    """
    collection = models.ForeignKey('collection.Collection')
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=100)

    class Meta:
        """Defines Metaparameters of the model."""
        abstract = True


class Annotation(models.Model):
    """The common base for Point and Whole image annotations.
    """
    image = models.ForeignKey('catamidb.Image')
    label = models.ForeignKey('annotations.AnnotationCode')
    labeller = models.ForeignKey(User)
    mtime = models.DateTimeField(auto_now=True, null=True)
    ctime = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Defines Metaparameters of the model."""
        abstract = True


#POINT_METHODOLOGIES = (
#    (0, 'Random Point'),
#    (1, 'Stratified'),
#    (2, 'Fixed Pattern'),
#)
POINT_METHODOLOGIES = (
    (0, 'N random points'),
    (1, 'Regular grid (N points across)'),
    (2, 'Regular grid (N points down)'),
    (3, 'Spectrometer FOV patch (9 points)'),
    (4, 'Point click AND N Random points')
)


#def random_point(annotation_set, image, labeller):
#    import random
#    for i in xrange(annotation_set.count):
#        x = random.random()
#        y = random.random()
#
#        ann = PointAnnotation()
#
#        ann.annotation_set = annotation_set
#        ann.image = image
#        ann.labeller = labeller
#        ann.x = x
#        ann.y = y
#
#        ann.label = AnnotationCode.objects.get(id=1) # not considered
#        ann.level = 0 # not considered
#
#        ann.save()
#
#def fixed_grid(annotation_set, image, labeller):

def add_point(annotation_set, image, labeller, x, y):
    ann = PointAnnotation()
    ann.annotation_set = annotation_set
    ann.image = image
    ann.labeller = labeller
    ann.x = x
    ann.y = y
    ann.label = AnnotationCode.objects.get(id=1) # not considered
    ann.level = 0 # not considered

    ann.save() #test


class PointAnnotationManager(models.Manager):
    """Manager for PointAnnotationSet.

    Helps create the pointannotations for images
    within the set.
    """

    def create_annotations(self, annotation_set, image, labeller):

        if annotation_set.methodology == 0: # random
            #random_point(annotation_set, image, labeller)
            import random

            for i in xrange(annotation_set.count):
                x = random.random()
                y = random.random()
                add_point(annotation_set, image, labeller, x, y)

        elif annotation_set.methodology == 1 or annotation_set.methodology == 2: # fixed grid
            imgx2y = 1360.0 / 1024.0 # TODO: this is dodgy!!! Should be robust to different aspect ratios
            if annotation_set.methodology == 1:
                xsep = 1.0 / annotation_set.count
                ysep = xsep * imgx2y
            elif annotation_set.methodology == 2:
                ysep = 1.0 / annotation_set.count
                xsep = ysep / imgx2y

            nx = int(1 / xsep)
            ny = int(1 / ysep)
            xstart = (1 - (nx-1) * xsep) / 2
            ystart = (1 - (ny-1) * ysep) / 2

            for i in xrange(0,nx) :
                for j in xrange(0,ny) :
                    x = xstart + i*xsep
                    y = ystart + j*ysep
                    add_point(annotation_set, image, labeller, x, y)


        elif annotation_set.methodology == 3:
            add_point(annotation_set, image, labeller, 0.51252,0.54757)
            add_point(annotation_set, image, labeller, 0.55997,0.54757)
            add_point(annotation_set, image, labeller, 0.46506,0.54757)
            add_point(annotation_set, image, labeller, 0.51252,0.6106)
            add_point(annotation_set, image, labeller, 0.51252,0.48455)
            add_point(annotation_set, image, labeller, 0.54607,0.59214)
            add_point(annotation_set, image, labeller, 0.54607,0.50301)
            add_point(annotation_set, image, labeller, 0.47896,0.59214)
            add_point(annotation_set, image, labeller, 0.47896,0.50301)

        elif annotation_set.methodology == 4: # random
            # Random + click select
            #random_point(annotation_set, image, labeller)
            import random

            for i in xrange(annotation_set.count):
                x = random.random()
                y = random.random()
                add_point(annotation_set, image, labeller, x, y)



class PointAnnotationSetManager(models.Manager):
    def create_annotation_set (self, user, name, methodology, n, c_id):
        annotation_set = PointAnnotationSet()
        annotation_set.methodology = int(methodology)
        annotation_set.collection = Collection.objects.get(pk=int(c_id))
        annotation_set.count = int(n)
        annotation_set.name = name
        annotation_set.owner = user

        # save the collection so we can associate images with it
        annotation_set.save()

        apply_pointannotationset_permissions(user, annotation_set)
        #TODO apply permissions
        #authorization.apply_pointannotationset_permissions(user, annotation_set)
        #print annotation_set
        asid = annotation_set.id
        msg = "Your Annotation set has been created successfully!"
        #print asid
        return asid, msg


class PointAnnotationSet(AnnotationSet):
    """Point Annotation Container.

    Relates a collection/workset to a set of annotations and
    the methodologies used to create them.
    """
    # a choice of methodology
    methodology = models.IntegerField(choices=POINT_METHODOLOGIES)
    # an integer parameter (for random selection, stratified etc)
    # not always used
    count = models.IntegerField()

    def __unicode__(self):
        return "{0} ({1} - {2}: {3})".format(
                self.name,
                self.collection.name,
                POINT_METHODOLOGIES[self.methodology][1],
                self.count
            )

    class Meta:
        unique_together = (('owner', 'name', 'collection'), )
        permissions = (
                ('create_pointannotationset', 'Create a pointannotation set'),
                ('view_pointannotationset', 'View this pointannotation set'),
                ('update_pointannotationset', 'Update this pointannotation set'),
            )



LEVELS = (
    (0, "Not Specified"),
    (1, "Primary"),
    (2, "Secondary"),
    (3, "Tertiary"),
)


class PointAnnotation(Annotation):
    """A Point annotation.

    Contains position within the image (as a percent from top left) and
    the set to which it belongs.
    """
    annotation_set = models.ForeignKey(
        PointAnnotationSet,
        related_name='images'
    )
    x = models.FloatField()
    y = models.FloatField()
    level = models.IntegerField(choices=LEVELS)
    qualifiers = models.ManyToManyField(
        'QualifierCode',
        related_name='point_annotations'
    )

    objects = PointAnnotationManager()


class ImageAnnotationSet(AnnotationSet):
    """A Whole Image annotation set.
    """

    class Meta:
        unique_together = (('owner', 'name', 'collection'), )


COVER = (
    (0, "C > 80%"),
    (1, "60% < C < 80%"),
    (2, "40% < C < 60%"),
    (3, "20% < C < 40%"),
    (4, "C < 20%"),
)


class ImageAnnotation(Annotation):
    """A Whole Image annotation.

    Contains the percent cover for the dominant class.
    """
    annotation_set = models.ForeignKey(
        ImageAnnotationSet,
        related_name='images'
    )
    cover = models.IntegerField(choices=COVER)
    qualifiers = models.ManyToManyField(
        'QualifierCode',
        related_name='image_annotations'
    )

catamidb/templates/Force/AddCampaign.html
<form action="" method="post"> {% csrf_token %}
    {{ form.non_field_errors }}

    <div class="fieldWrapper">
        {{ form.description.errors }}
        <label for="id_description">Description:</label>
        {{ form.description }}
    </div>

    <div class="fieldWrapper">
        {{ form.associatedResearchers.errors }}
        <label for="id_associatedResearchers">Associated Researchers:</label>
        {{ form.associatedResearchers }}
    </div>

    <div class="fieldWrapper">
        {{ form.associatedPublications.errors }}
        <label for="id_associatedPublications">Associated Publications:</label>
        {{ form.associatedPublications }}
    </div>

    <div class="fieldWrapper">
        {{ form.associatedResearchGrant.errors }}
        <label for="id_associatedResearchGrant">Associated Research Grant:</label>
        {{ form.associatedResearchGrant }}
    </div>

    <div class="fieldWrapper">
        {{ form.dateStart.errors }}
        <label for="id_dateStart">Start Date:</label>
        {{ form.dateStart }}
    </div>

    <div class="fieldWrapper">
        {{ form.dateEnd.errors }}
        <label for="id_dateEnd">End Date:</label>
        {{ form.dateEnd }}
    </div>

    <p><input type="submit" value="Save Campaign" /></p>
</form>

catamidb/templates/Force/CampaignList.html
{% if campaignList %}
    <ul>
        {% for campaign in campaignList %}
            <li>{{ campaign.description }} - {{  campaign.associatedResearchers }} - {{campaign.associatedPublications}} - {{campaign.associatedResearchGrant}} - {{campaign.dateStart}} - {{campaign.dataEnd}} </li>
        {% endfor %}
    </ul>
{% else %}

    <p>No campaigns are available.</p>
{% endif %}

catamidb/templates/Force/DeploymentMap.html
{% extends "base.html" %}

{% block sidebar %}
  <div id="sidebar-nav" class="span3" style="padding-left:10px;">

    <h1>Deployment Map</h1>  
    <div class="well well-small" style="align:center;">

      <p class="lead"> Deployment Map</p>
      <p>options</p>
    </div><!--/.well -->
  </div>
{% endblock %}

{% block content_header %}
  <ul class="breadcrumb">
    <li><a href="/data">Data</a>  
    <li><a href="/data/deployments/"><span class="divider">></span> Deployment List</a></li>
    <li class="active"><span class="divider">></span> Deployment Map</li>
  </ul>
{% endblock %}

<!--{% block breadcrumbs %}
  <li class="active">AUV Deployment List</li>
{% endblock %}-->

{% block content %}
  <!--{% if latest_deployment_list %}
    <table class="table table-striped">
      <tbody>
          {% for deployment in latest_deployment_list %}
            <tr>
              <td>{{deployment.start_position.geojson}}</td>
            <tr>

          {% endfor %}
      </tbody>
    </table>
  {% else %}
      <p>No deployments are available.</p>
  {% endif %}-->
  <div id='map_container2'></div>
  

{% endblock %}

{% block add_script %}
    <script src='{{ STATIC_URL }}assets/openlayers/OpenLayers.js'> </script>
    <script src='{{ STATIC_URL }}assets/esriOceanBasemap/map.js'></script>
    
    <script type="text/javascript">
        var lon = 138;
        var lat = -35;
        var zoom = 4;
        var map, layer;

 function init(){

            map = new OpenLayers.Map('map_container2');
            layer = new OpenLayers.Layer.WMS( "OpenLayers WMS", 
                    "http://vmap0.tiles.osgeo.org/wms/vmap0",
                    {layers: 'basic'} );
            
            map.addLayer(layer);
            map.setCenter(new OpenLayers.LonLat(lon, lat), zoom);
var geojson_data = '{ "type": "FeatureCollection", "features": [ {"geometry": { "type": "GeometryCollection", "geometries": [\
{% for deployment in latest_deployment_list %}{% if not forloop.last %}{{deployment.start_position.geojson|safe}},{% else %}{{deployment.start_position.geojson|safe}}{% endif %}{% endfor %}] }, "type": "Feature", "properties": {}} ] }';
           
           var geojson_format = new OpenLayers.Format.GeoJSON();
           var featurecollection = geojson_format.read(geojson_data);
           
           var vector_layer = new OpenLayers.Layer.Vector(); 
           map.addLayer(vector_layer);
           vector_layer.addFeatures(geojson_format.read(geojson_data));

        }
    </script>
{% endblock %}

catamidb/templates/Force/annotationview.html
{% extends "base-nosidebar.html" %}

{% block sidebar %}
{% endblock %}

{% block content_header %}
  <ul class="breadcrumb">
    <li><a href="/data/">Data</a> <span class="divider">></span></li>
    <li><a href="/data/campaigns/">Campaign List</a> <span class="divider">></span></li>
    <li><a href="/data/campaigns/{{auvdeployment_object.campaign.id}}">{{auvdeployment_object.campaign.short_name}}</a> <span class="divider">></span></li>
    <li><a href="/data/auvdeployments/{{auvdeployment_object.id}}">{{auvdeployment_object.short_name}}</a> <span class="divider">></span></li>
    <li class="active">Annotation View</li>
  </ul>
  
{% endblock %}

{% block content %}


<h3>AUV Annotation Viewer</h3>

<div class="row">
	<div class="span9">
		<div style="position:relative;width:800px;">
	     	<img src="{{annotated_image.left_image_reference}}" width="800">
	     	{% for note in styled_annotation_data %}
	     		{{note|safe}}
	     	{% endfor %}
<!-- 	     	<p style="z-index:100; position:absolute;  color:white; font-size:12px; font-weight:normal; left:50%; top:50%;">sand</p> -->
		</div>
     </div>
</div>
<div class="row">
		<div>
	     <a href= "/data/auvdeployments/{{auvdeployment_object.id}}/annotationview/{{image_index_next}}">Next</a>
	     <div class="well">
	     <h5>Image Reference</h5>
	     <p style="word-wrap: break-word;">{{annotated_image.left_image_reference}}</p>
	     </div></div>
</div>
     <!--
<div class="span3">
        <table class="table table-striped table-condensed">
          <thead>
            <tr>
              <th>Label</th>
              <th>Position</th>
            </tr>
          </thead>
          <tbody>
    
              {% for note in annotation_list %}
                <tr>
                  <td>{{note.code}}</v>
                  <td>{{note.point}}</td>
                <tr>
    
              {% endfor %}
          </tbody>
        </table>
    </div>
</div>
-->
 
{% endblock %}

{% block add_script %}
{% endblock %}

catamidb/templates/Force/auvDeploymentMap.html
{% extends "base.html" %}

{% block sidebar %}
  <div id="sidebar-nav" class="span3" style="padding-left:10px;">

    <h1>Deployment Map</h1>  
    <div class="well well-small" style="align:center;">

      <p class="lead">AUV Map</p>
      <p>options</p>
    </div><!--/.well -->
  </div>
{% endblock %}

{% block content_header %}
  <ul class="breadcrumb">
    <li class="active">AUV Deployment List</li>
  </ul>
{% endblock %}

<!--{% block breadcrumbs %}
  <li class="active">AUV Deployment List</li>
{% endblock %}-->

{% block content %}
  {% if latest_auvdeployment_list %}
    <table class="table table-striped">
      <tbody>
          {% for auvdeployment in latest_auvdeployment_list %}
            <tr>
              <td>{{auvdeployment.transect_shape.geojson}}</td>
            <tr>

          {% endfor %}
      </tbody>
    </table>
  {% else %}
      <p>No auvdeployments are available.</p>
  {% endif %}
  <div id='map_container2'></div>
  

{% endblock %}

{% block add_script %}
    <script src='{{ STATIC_URL }}assets/openlayers/OpenLayers.js'> </script>
    <script src='{{ STATIC_URL }}assets/esriOceanBasemap/map.js'></script>
    
    <script type="text/javascript">
        var lon = 148;
        var lat = -41;
        var zoom = 6;
        var map, layer;

 function init(){
            map = new OpenLayers.Map( 'map_container2' );
            layer = new OpenLayers.Layer.WMS( "OpenLayers WMS", 
                    "http://vmap0.tiles.osgeo.org/wms/vmap0",
                    {layers: 'basic'} );
            map.addLayer(layer);
            map.setCenter(new OpenLayers.LonLat(lon, lat), zoom);
var geojson_data = '{ "type": "FeatureCollection", "features": [ {"geometry": { "type": "GeometryCollection", "geometries": [\
{% for auvdeployment in latest_auvdeployment_list %}{% if not forloop.last %}{{auvdeployment.transect_shape.geojson|safe}},{% else %}{{auvdeployment.transect_shape.geojson|safe}}{% endif %}{% endfor %}] }, "type": "Feature", "properties": {}} ] }';
           
           var geojson_format = new OpenLayers.Format.GeoJSON();
           var featurecollection = geojson_format.read(geojson_data);
           
           var vector_layer = new OpenLayers.Layer.Vector(); 
           map.addLayer(vector_layer);
           vector_layer.addFeatures(geojson_format.read(geojson_data));

        }
    </script>
{% endblock %}

catamidb/templates/Force/auvdeployment_display.html
{% extends "base-nosidebar.html" %}

{% load force_extras %}

{% block add_styles %}
    <link rel="stylesheet" href="{{ STATIC_URL }}assets/css/leaflet.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}assets/css/Control.MiniMap.css" />
{% endblock %}
{% block insert_style %}
		.leaflet-control-zoom-fullscreen { background-image: url({{ STATIC_URL }}assets/css/images/icon-fullscreen.png); }
		.leaflet-control-zoom-fullscreen.last { margin-top: 5px }
		#leaflet_container:-webkit-full-screen { width: 100% !important; height: 100% !important; }
		#leaflet_container:-moz-full-screen { width: 100% !important; height: 100% !important; }
		#leaflet_container:full-screen { width: 100% !important; height: 100% !important; }
		.info {
			padding: 0px 8px;
			align: right;
			font: 14px/16px Helvetica, Arial, sans-serif;
			background: white;
			background: rgba(255,255,255,0.8);
			box-shadow: 0 0 15px rgba(0,0,0,0.2);
			border-radius: 5px;
		}
		.legend {
			text-align: left;
			line-height: 18px;
			color: #555;
		}
		.legend i {
			width: 18px;
			height: 18px;
			float: left;
			margin-right: 8px;
			opacity: 0.7;
		}
		
		#loading {
		  width: 100%;
		  height: 100%;
		  <!--
top: 0px;
		  left: 0px;
		  position: fixed;
-->
		  display: block;
		  opacity: 0.7;
		  background-color: #fff;
		  z-index: 99;
		  text-align: center;
		}
		
		#loading-image {
<!--
		  position: absolute;
		  top: 100px;
		  left: 240px;
-->
		  z-index: 100;
		}
{% endblock %} 

{% block content_header %}

	<div class="row">

	  <ul class="breadcrumb">
	    <li><a href="/data/">Data</a> <span class="divider">></span></li>
	    <li><a href="/data/campaigns/">Campaign List</a> <span class="divider">></span></li>
	    <li><a href="/data/campaigns/{{auvdeployment_object.campaign.id}}">{{auvdeployment_object.campaign.short_name}}</a> <span class="divider">></span></li>
	    <li class="active">{{auvdeployment_object.short_name}}</li>
	  </ul>
	</div>
  
{% endblock %}

	{% block content %}
		<div class="row-fluid" id="loading">
		  <div class="row"><img id="loading-image" src="{{ STATIC_URL }}assets/img/timefish.gif" alt="Loading..." /></div>
		   <br>
		   <div class="row"><h2>Loading...</h2></div>
		</div>
		
	{% if auvdeployment_object %}
		<div id="success"></div>
		<div id="error"></div>
	{% endif %}

{% endblock %}

{% block add_script %}

	<script>
		$('#loading')
		    .hide()  // hide it initially
		    .ajaxStart(function() {
		        $(this).show();
		    })
		    .ajaxStop(function() {
		        $(this).hide();
		    })
		;
	</script>
	<script>
		$("#success").load("/data/auvdeployments/{{auvdeployment_object.id}}/detail", function(response, status, xhr) {
		  if (status == "error") {
		    var msg = "Sorry but there was an error: ";
		    $("#error").html("Tried to load /data/auvdeployments/{{auvdeployment_object.id}}/detail/  <br>" + msg + xhr.status + " " + xhr.statusText);
		  }
		});
	</script>

{% endblock %}

catamidb/templates/Force/bruvDeploymentIndex.html
{% extends "base.html" %}


{% block sidebar %}
  <div id="sidebar-nav" class="span3" style="padding-left:10px;">

    <h1>BRUV Deployment</h1>  
    <div class="well well-small" style="align:center;">

      <p class="lead">BRUV List</p>
      <p>options</p>
    </div><!--/.well -->
  </div>
{% endblock %}

{% block content_header %}
  <ul class="breadcrumb">
    <li class="active">BRUV Deployment List</li>
  </ul>
{% endblock %}

<!--{% block breadcrumbs %}
  <li class="active">AUV Deployment List</li>
{% endblock %}-->

{% block content %}
  {% if latest_bruvdeployment_list %}
    <table class=table table-striped">
      <thead>
        <tr>
          <th>Start Time</th>
          <th>End Time</th>
          <th>Min Depth</th>
          <th>Max Depth</th>
          <th>Mission Aim</th>
          <th>Start Location</th>
          <th>Related Campaign</th>
        </tr>
      </thead>
      <tbody>

          {% for bruvdeployment in latest_bruvdeployment_list %}
            <tr>
              <td>{{bruvdeployment.start_time_stamp}}</td>
              <td>{{bruvdeployment.end_time_stamp}}</td>
              <td>{{bruvdeployment.min_depth}}</td>
              <td>{{bruvdeployment.max_depth}}</td>
              <td>{{bruvdeployment.mission_aim}}</td>
              <td>{{bruvdeployment.start_position}}</td>
              <td><a href="/data/campaigns/{{bruvdeployment.campaign.id}}" class="btn btn-large btn-primary">Campaign</a> <br><br>
                  <a href="/data/bruvdeployments/{{bruvdeployment.id}}" class="btn btn-large btn-primary">Detail</a></td>

            <tr>

          {% endfor %}
      </tbody>
    </table>
  {% else %}
      <p>No BRUV deployments are available.</p>
  {% endif %}
{% endblock %}

catamidb/templates/Force/data_missing.html
{% extends "base.html" %}


{% block sidebar %}
  <div id="sidebar-nav" class="span3" style="padding-left:10px;">

    <h1>Data</h1>  
    <div class="well well-small" style="align:center;">

      <p class="lead">Data Error</p>
      <p>options</p>
    </div><!--/.well -->

  </div>
{% endblock %}

{% block content_header %}
  <ul class="breadcrumb">
    <li><a href="/data/">Data</a> <span class="divider">></span></li>
  </ul>
  
{% endblock %}

{% block content %}
    <div class="alert">
      <strong>Warning!</strong> The data you have requested cannot be found.  This might be your fault or it might be our fault
    </div>
{% endblock %}

{% block add_script %}
{% endblock %}